* Resources I used
** Actions and Github OICD https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/
** Nix in github actions https://www.reddit.com/r/Nix/comments/198c3oh/run_nix_flake_on_github_action_to_deploy_python/
** Making a Github App https://docs.github.com/en/enterprise-cloud@latest/apps/creating-github-apps/writing-code-for-a-github-app/quickstart
** Reusable workflows https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#onworkflow_callinputs
** CDK Tut https://docs.aws.amazon.com/cdk/v2/guide/hello-world.html
* Notes
** Actions Github
Organazatins are case sensitive for the trust policy of the role yharnix=!Yharnix
** Setting up OIDC with Github and AWS
openssl s_client -servername keys.example.com -showcerts -connect keys.example.com:443
openssl s_client -servername token.actions.githubusercontent.com -showcerts -connect token.actions.githubusercontent.com:443
*

** S3 pre signed URL
Using Boto3 is the best way to generate presigend URLs I found
When sending the post request the name of the file uploaded and the key have to be the same, bacisally you have to know the name of the file in advance to do a s3 pre-signed url upload

I am thinking you should zip the repo and send that up to s3

Also you can make a pre sigend url of any s3 bucket regardless of permissions, the error will occuer when you try to use the URL you will get permission denied if lambda did not have the correc execution role

** Succesfuly have an API that can generate a pre signed url, right now I want to customize the pre sigend url to have a custom name for the objec upload containg a query string.

- This presigned url can now be generated with a custom name provided for the object name.

- Next up is a Github actions script that zips up the entire repo and can upload to s3 with this presigned URL


** In curl to send the contents of a file use @upload.zip instead of upload.zip otherwise the name of the file is used not the contents


** API Gateway
when using proxy, all headers are passed to the lambda function so if you want to add defined query parameters you can not use the CDK fucntion LambdaRestApi and have to define your own headers

** Github APP
This is the heart of this project
I can host my github app on AWS receive events and web hooks from Github, this app will just be a docker setup behind fargate and a load balancer.  What happens when a pr is made it will trigger some lambda function and start just building up a whole eco system with the prs code change and when finished publish the link to the pr chat as well as to the web app
** [#A] Milestone, custom broker part1 <2025-10-07 Tue>
This was a big milestone, I can now send aws credentials based on an API call to a lambda function, I can then check this lambda function and make sure the sender si an authenticated user by a backed database
* Import features [0/2]
To start I am just going to suport simple app stack, in this case i will support FastAPI, React, Postgres because this is what my app will be built with so it will make testing easier.
- [ ] Diagram :: Make a diagram for this
- [ ] Major Goal :: A App that users log into with Github, choose repositories that have poetry python projects, on PR I kick off a pipeline to generate a ephereal prod environment for them. 
  - [ ] Feature 1 :: Github App that detects PR app will be in python (prs will somehow trigger a workflow in AWS and start kicking off a prod deployments)
  - [ ] Feature 2 :: When the deployment is finished put the dns link into the pr chat
  - [ ] Feature 3 :: All these deployments should be accesible by the user for a full history, and at any point can spin up an old deployment
- [ ] Major Goal 2 :: Allow Users so specify docker files and nix derivations on their own to work for a wide range of users


  

* Github Setup

** Org -> Yharnix

*** repo -> CDK for needed infrastructure

*** TODO ci -> Very important setup here, all my ci/cd scrpits
THis will also provision resources to AWS here so uber imporant 

*** Github App -> detects web hooks and such

*** FastAPI and React APP that hosts a central place for Github Auth and repo tracking



* [[file:~/org-roam/20251009222039-typescript.org][Typescript]]

* Github App Auth
** Generate a JWT to use for API calls

** Use this to send over the jwt you generated with python
curl --request POST \
--url "https://api.github.com/app/installations/INSTALLATION_ID/access_tokens" \
--header "Accept: application/vnd.github+json" \
--header "Authorization: Bearer JWT" \
--header "X-GitHub-Api-Version: 2022-11-28"

** use this to get to make an api call to git hub
curl --request GET \
--url "https://api.github.com/meta" \
--header "Accept: application/vnd.github+json" \
--header "Authorization: Bearer <auth_token>" \
--header "X-GitHub-Api-Version: 2022-11-28"

** Make api calls examples


curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <token> " \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/orgs/yharnix/repos

** Run smee 

* New Project Pipeline
- [X] Step 1 :: Via the api on install create a branch and then a PR to add a custom action script to the repo
- [X] Step 2 :: Somehow detect if this pr is approved on the branch
- [ ] Step 3 :: After a merge trigger the workflow file based on a PR webhook
- [ ] Step 4 :: Have my comprehensive Github Actions Script pipeline setup to start building some AWS infra based on the customer 

* CDK
Make sure you first have your profile authenticated
aws sso login --profile admin

** Bootstrap the environment
only run this once to set up an initial stack
cdk bootstrap --profile admin

** Build manually to catche type errors
npm run build
** List cdk stacks in your app
cdk list 
** Time to synthesize 
cdk synth
** Deploy
cdk deploy --profile admin 
** See a diff when you make a change
cdk diff --profile admin
** Tear it all down
cdk destroy --profile admin

** CDK needs access to ssm:parameter_store and s3
* Model my github after this guy
https://github.com/rjones18



About the job

Overview:

 At Blankfactor, we’re looking for a skilled and proactive AWS DevOps Engineer to join our growing team. In this role, you’ll be responsible for building and maintaining cloud infrastructure, automation pipelines, and deployment strategies to support high-performance applications. You’ll work closely with engineering teams to streamline development workflows and ensure system reliability, scalability, and security.

Key Responsibilities:

    Design, implement, and manage scalable AWS infrastructure using Infrastructure as Code (IaC) tools like Terraform or CloudFormation
    Build and maintain CI/CD pipelines to enable efficient, reliable software delivery
    Monitor systems and troubleshoot issues in production and development environments
    Implement and enforce security best practices, including identity and access management, encryption, and network protection
    Automate operational tasks and deployments to improve speed and efficiency
    Collaborate with developers, architects, and QA to ensure seamless integration and delivery
    Support disaster recovery planning, cost optimization, and performance tuning

Qualifications:

    4+ years of experience in DevOps or cloud engineering roles
    Strong hands-on experience with AWS services (EC2, ECS, EKS, Lambda, S3, RDS, etc.)
    Proficiency in Infrastructure as Code tools, preferably Terraform
    Experience with CI/CD tools such as Jenkins, GitHub Actions, GitLab CI, or CircleCI
    Scripting skills with Python, Bash, or similar
    Solid understanding of networking, security principles, and monitoring tools (e.g., CloudWatch, Prometheus, Grafana)
    Experience with Docker and container orchestration tools like Kubernetes is a plus
    Excellent communication and collaboration skills
    English level: B2+ or higher

Nice to Have:

    AWS Certifications (e.g., AWS Certified DevOps Engineer – Professional)
    Experience in regulated environments (e.g., fintech, healthcare)
    Familiarity with observability stacks and logging tools (ELK, Datadog, etc.)



I am looking for a role for a role for DevOps, In my internship I provided great valuet to my team by being the only one versed in Gitlab CI/CD and helped streamline the conversion of Jenkins to Gitlab CI/CD.  I recentrly got my AWS SAA ceart and I am actively backing up this cert with AWS work every day I have a project I am working on the involves spinning up ephemeral testing environments whenever PRS are made in a github repos, this involes many AWS services and I am learning so much, I just applied to the DevOps engineer positons, I would love to chat with you and maybe hear about your experience in the Industry as a Senior Devops engineer at Blankfactor, I am a scrappy and quick an although I do not meet everything in the job descripiton I will learn quick    


* Apps out


* CDK in github actions

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          npm install -g aws-cdk
      - name: Run AWS CLI commands
        run: |
          cdk --version
          # echo "oh yeah ${{needs.auth-and-run.outputs}}"
          # aws sts get-caller-identity
          # aws s3 ls
      - name: Deploy to AWS
        working-directory: infra/cdk-workshop
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi 
          cdk deploy --require-approval=never
  build_image:
    uses: Yharnix/ci/.github/workflows/docker_build.yml@master 
          

* Security
- [ ] ECR :: ECR must not allow tag overwriting, explitly state not allowing mutable tag uploads
